//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace cliente.servicioChat {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ipOperationCompleted;
        
        private System.Threading.SendOrPostCallback puertoOperationCompleted;
        
        private System.Threading.SendOrPostCallback entregaConectadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambiarContraseñaOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarMensajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback desconectarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::cliente.Properties.Settings.Default.cliente_servicioChat_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event ipCompletedEventHandler ipCompleted;
        
        /// <remarks/>
        public event puertoCompletedEventHandler puertoCompleted;
        
        /// <remarks/>
        public event entregaConectadosCompletedEventHandler entregaConectadosCompleted;
        
        /// <remarks/>
        public event registrarCompletedEventHandler registrarCompleted;
        
        /// <remarks/>
        public event cambiarContraseñaCompletedEventHandler cambiarContraseñaCompleted;
        
        /// <remarks/>
        public event enviarMensajeCompletedEventHandler enviarMensajeCompleted;
        
        /// <remarks/>
        public event desconectarCompletedEventHandler desconectarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int login(string user, string pass, string ip) {
            object[] results = this.Invoke("login", new object[] {
                        user,
                        pass,
                        ip});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string user, string pass, string ip) {
            this.loginAsync(user, pass, ip, null);
        }
        
        /// <remarks/>
        public void loginAsync(string user, string pass, string ip, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        user,
                        pass,
                        ip}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ip(string user) {
            object[] results = this.Invoke("ip", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ipAsync(string user) {
            this.ipAsync(user, null);
        }
        
        /// <remarks/>
        public void ipAsync(string user, object userState) {
            if ((this.ipOperationCompleted == null)) {
                this.ipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnipOperationCompleted);
            }
            this.InvokeAsync("ip", new object[] {
                        user}, this.ipOperationCompleted, userState);
        }
        
        private void OnipOperationCompleted(object arg) {
            if ((this.ipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ipCompleted(this, new ipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/puerto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int puerto(string user) {
            object[] results = this.Invoke("puerto", new object[] {
                        user});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void puertoAsync(string user) {
            this.puertoAsync(user, null);
        }
        
        /// <remarks/>
        public void puertoAsync(string user, object userState) {
            if ((this.puertoOperationCompleted == null)) {
                this.puertoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpuertoOperationCompleted);
            }
            this.InvokeAsync("puerto", new object[] {
                        user}, this.puertoOperationCompleted, userState);
        }
        
        private void OnpuertoOperationCompleted(object arg) {
            if ((this.puertoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.puertoCompleted(this, new puertoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/entregaConectados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string entregaConectados() {
            object[] results = this.Invoke("entregaConectados", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void entregaConectadosAsync() {
            this.entregaConectadosAsync(null);
        }
        
        /// <remarks/>
        public void entregaConectadosAsync(object userState) {
            if ((this.entregaConectadosOperationCompleted == null)) {
                this.entregaConectadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnentregaConectadosOperationCompleted);
            }
            this.InvokeAsync("entregaConectados", new object[0], this.entregaConectadosOperationCompleted, userState);
        }
        
        private void OnentregaConectadosOperationCompleted(object arg) {
            if ((this.entregaConectadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.entregaConectadosCompleted(this, new entregaConectadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int registrar(string username, string password) {
            object[] results = this.Invoke("registrar", new object[] {
                        username,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void registrarAsync(string username, string password) {
            this.registrarAsync(username, password, null);
        }
        
        /// <remarks/>
        public void registrarAsync(string username, string password, object userState) {
            if ((this.registrarOperationCompleted == null)) {
                this.registrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarOperationCompleted);
            }
            this.InvokeAsync("registrar", new object[] {
                        username,
                        password}, this.registrarOperationCompleted, userState);
        }
        
        private void OnregistrarOperationCompleted(object arg) {
            if ((this.registrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarCompleted(this, new registrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cambiarContraseña", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int cambiarContraseña(string user, string pass, string passvieja) {
            object[] results = this.Invoke("cambiarContraseña", new object[] {
                        user,
                        pass,
                        passvieja});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void cambiarContraseñaAsync(string user, string pass, string passvieja) {
            this.cambiarContraseñaAsync(user, pass, passvieja, null);
        }
        
        /// <remarks/>
        public void cambiarContraseñaAsync(string user, string pass, string passvieja, object userState) {
            if ((this.cambiarContraseñaOperationCompleted == null)) {
                this.cambiarContraseñaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambiarContraseñaOperationCompleted);
            }
            this.InvokeAsync("cambiarContraseña", new object[] {
                        user,
                        pass,
                        passvieja}, this.cambiarContraseñaOperationCompleted, userState);
        }
        
        private void OncambiarContraseñaOperationCompleted(object arg) {
            if ((this.cambiarContraseñaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambiarContraseñaCompleted(this, new cambiarContraseñaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarMensaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void enviarMensaje(string user, string mensaje, string sala) {
            this.Invoke("enviarMensaje", new object[] {
                        user,
                        mensaje,
                        sala});
        }
        
        /// <remarks/>
        public void enviarMensajeAsync(string user, string mensaje, string sala) {
            this.enviarMensajeAsync(user, mensaje, sala, null);
        }
        
        /// <remarks/>
        public void enviarMensajeAsync(string user, string mensaje, string sala, object userState) {
            if ((this.enviarMensajeOperationCompleted == null)) {
                this.enviarMensajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarMensajeOperationCompleted);
            }
            this.InvokeAsync("enviarMensaje", new object[] {
                        user,
                        mensaje,
                        sala}, this.enviarMensajeOperationCompleted, userState);
        }
        
        private void OnenviarMensajeOperationCompleted(object arg) {
            if ((this.enviarMensajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarMensajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/desconectar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int desconectar(string user, string sala) {
            object[] results = this.Invoke("desconectar", new object[] {
                        user,
                        sala});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void desconectarAsync(string user, string sala) {
            this.desconectarAsync(user, sala, null);
        }
        
        /// <remarks/>
        public void desconectarAsync(string user, string sala, object userState) {
            if ((this.desconectarOperationCompleted == null)) {
                this.desconectarOperationCompleted = new System.Threading.SendOrPostCallback(this.OndesconectarOperationCompleted);
            }
            this.InvokeAsync("desconectar", new object[] {
                        user,
                        sala}, this.desconectarOperationCompleted, userState);
        }
        
        private void OndesconectarOperationCompleted(object arg) {
            if ((this.desconectarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.desconectarCompleted(this, new desconectarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ipCompletedEventHandler(object sender, ipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void puertoCompletedEventHandler(object sender, puertoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class puertoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal puertoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void entregaConectadosCompletedEventHandler(object sender, entregaConectadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class entregaConectadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal entregaConectadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void registrarCompletedEventHandler(object sender, registrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void cambiarContraseñaCompletedEventHandler(object sender, cambiarContraseñaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambiarContraseñaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambiarContraseñaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void enviarMensajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void desconectarCompletedEventHandler(object sender, desconectarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class desconectarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal desconectarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591