//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cliente.sservicioChat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sservicioChat.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        cliente.sservicioChat.loginResponse login(cliente.sservicioChat.loginRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ip", ReplyAction="*")]
        cliente.sservicioChat.ipResponse ip(cliente.sservicioChat.ipRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/puerto", ReplyAction="*")]
        cliente.sservicioChat.puertoResponse puerto(cliente.sservicioChat.puertoRequest request);
        
        // CODEGEN: Generating message contract since element name entregaConectadosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/entregaConectados", ReplyAction="*")]
        cliente.sservicioChat.entregaConectadosResponse entregaConectados(cliente.sservicioChat.entregaConectadosRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar", ReplyAction="*")]
        cliente.sservicioChat.registrarResponse registrar(cliente.sservicioChat.registrarRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cambiarContraseña", ReplyAction="*")]
        cliente.sservicioChat.cambiarContraseñaResponse cambiarContraseña(cliente.sservicioChat.cambiarContraseñaRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarMensaje", ReplyAction="*")]
        cliente.sservicioChat.enviarMensajeResponse enviarMensaje(cliente.sservicioChat.enviarMensajeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(cliente.sservicioChat.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ip;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string user, string pass, string ip) {
            this.user = user;
            this.pass = pass;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(cliente.sservicioChat.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(int loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ip", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.ipRequestBody Body;
        
        public ipRequest() {
        }
        
        public ipRequest(cliente.sservicioChat.ipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public ipRequestBody() {
        }
        
        public ipRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ipResponse", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.ipResponseBody Body;
        
        public ipResponse() {
        }
        
        public ipResponse(cliente.sservicioChat.ipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ipResult;
        
        public ipResponseBody() {
        }
        
        public ipResponseBody(string ipResult) {
            this.ipResult = ipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class puertoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="puerto", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.puertoRequestBody Body;
        
        public puertoRequest() {
        }
        
        public puertoRequest(cliente.sservicioChat.puertoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class puertoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public puertoRequestBody() {
        }
        
        public puertoRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class puertoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="puertoResponse", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.puertoResponseBody Body;
        
        public puertoResponse() {
        }
        
        public puertoResponse(cliente.sservicioChat.puertoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class puertoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int puertoResult;
        
        public puertoResponseBody() {
        }
        
        public puertoResponseBody(int puertoResult) {
            this.puertoResult = puertoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class entregaConectadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="entregaConectados", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.entregaConectadosRequestBody Body;
        
        public entregaConectadosRequest() {
        }
        
        public entregaConectadosRequest(cliente.sservicioChat.entregaConectadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class entregaConectadosRequestBody {
        
        public entregaConectadosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class entregaConectadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="entregaConectadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.entregaConectadosResponseBody Body;
        
        public entregaConectadosResponse() {
        }
        
        public entregaConectadosResponse(cliente.sservicioChat.entregaConectadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class entregaConectadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string entregaConectadosResult;
        
        public entregaConectadosResponseBody() {
        }
        
        public entregaConectadosResponseBody(string entregaConectadosResult) {
            this.entregaConectadosResult = entregaConectadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.registrarRequestBody Body;
        
        public registrarRequest() {
        }
        
        public registrarRequest(cliente.sservicioChat.registrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public registrarRequestBody() {
        }
        
        public registrarRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.registrarResponseBody Body;
        
        public registrarResponse() {
        }
        
        public registrarResponse(cliente.sservicioChat.registrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int registrarResult;
        
        public registrarResponseBody() {
        }
        
        public registrarResponseBody(int registrarResult) {
            this.registrarResult = registrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cambiarContraseñaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cambiarContraseña", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.cambiarContraseñaRequestBody Body;
        
        public cambiarContraseñaRequest() {
        }
        
        public cambiarContraseñaRequest(cliente.sservicioChat.cambiarContraseñaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cambiarContraseñaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string passvieja;
        
        public cambiarContraseñaRequestBody() {
        }
        
        public cambiarContraseñaRequestBody(string user, string pass, string passvieja) {
            this.user = user;
            this.pass = pass;
            this.passvieja = passvieja;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cambiarContraseñaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cambiarContraseñaResponse", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.cambiarContraseñaResponseBody Body;
        
        public cambiarContraseñaResponse() {
        }
        
        public cambiarContraseñaResponse(cliente.sservicioChat.cambiarContraseñaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cambiarContraseñaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cambiarContraseñaResult;
        
        public cambiarContraseñaResponseBody() {
        }
        
        public cambiarContraseñaResponseBody(int cambiarContraseñaResult) {
            this.cambiarContraseñaResult = cambiarContraseñaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensaje", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.enviarMensajeRequestBody Body;
        
        public enviarMensajeRequest() {
        }
        
        public enviarMensajeRequest(cliente.sservicioChat.enviarMensajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviarMensajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sala;
        
        public enviarMensajeRequestBody() {
        }
        
        public enviarMensajeRequestBody(string user, string mensaje, string sala) {
            this.user = user;
            this.mensaje = mensaje;
            this.sala = sala;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarMensajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviarMensajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public cliente.sservicioChat.enviarMensajeResponseBody Body;
        
        public enviarMensajeResponse() {
        }
        
        public enviarMensajeResponse(cliente.sservicioChat.enviarMensajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class enviarMensajeResponseBody {
        
        public enviarMensajeResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : cliente.sservicioChat.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<cliente.sservicioChat.Service1Soap>, cliente.sservicioChat.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cliente.sservicioChat.loginResponse cliente.sservicioChat.Service1Soap.login(cliente.sservicioChat.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public int login(string user, string pass, string ip) {
            cliente.sservicioChat.loginRequest inValue = new cliente.sservicioChat.loginRequest();
            inValue.Body = new cliente.sservicioChat.loginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.ip = ip;
            cliente.sservicioChat.loginResponse retVal = ((cliente.sservicioChat.Service1Soap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cliente.sservicioChat.ipResponse cliente.sservicioChat.Service1Soap.ip(cliente.sservicioChat.ipRequest request) {
            return base.Channel.ip(request);
        }
        
        public string ip(string user) {
            cliente.sservicioChat.ipRequest inValue = new cliente.sservicioChat.ipRequest();
            inValue.Body = new cliente.sservicioChat.ipRequestBody();
            inValue.Body.user = user;
            cliente.sservicioChat.ipResponse retVal = ((cliente.sservicioChat.Service1Soap)(this)).ip(inValue);
            return retVal.Body.ipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cliente.sservicioChat.puertoResponse cliente.sservicioChat.Service1Soap.puerto(cliente.sservicioChat.puertoRequest request) {
            return base.Channel.puerto(request);
        }
        
        public int puerto(string user) {
            cliente.sservicioChat.puertoRequest inValue = new cliente.sservicioChat.puertoRequest();
            inValue.Body = new cliente.sservicioChat.puertoRequestBody();
            inValue.Body.user = user;
            cliente.sservicioChat.puertoResponse retVal = ((cliente.sservicioChat.Service1Soap)(this)).puerto(inValue);
            return retVal.Body.puertoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cliente.sservicioChat.entregaConectadosResponse cliente.sservicioChat.Service1Soap.entregaConectados(cliente.sservicioChat.entregaConectadosRequest request) {
            return base.Channel.entregaConectados(request);
        }
        
        public string entregaConectados() {
            cliente.sservicioChat.entregaConectadosRequest inValue = new cliente.sservicioChat.entregaConectadosRequest();
            inValue.Body = new cliente.sservicioChat.entregaConectadosRequestBody();
            cliente.sservicioChat.entregaConectadosResponse retVal = ((cliente.sservicioChat.Service1Soap)(this)).entregaConectados(inValue);
            return retVal.Body.entregaConectadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cliente.sservicioChat.registrarResponse cliente.sservicioChat.Service1Soap.registrar(cliente.sservicioChat.registrarRequest request) {
            return base.Channel.registrar(request);
        }
        
        public int registrar(string username, string password) {
            cliente.sservicioChat.registrarRequest inValue = new cliente.sservicioChat.registrarRequest();
            inValue.Body = new cliente.sservicioChat.registrarRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            cliente.sservicioChat.registrarResponse retVal = ((cliente.sservicioChat.Service1Soap)(this)).registrar(inValue);
            return retVal.Body.registrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cliente.sservicioChat.cambiarContraseñaResponse cliente.sservicioChat.Service1Soap.cambiarContraseña(cliente.sservicioChat.cambiarContraseñaRequest request) {
            return base.Channel.cambiarContraseña(request);
        }
        
        public int cambiarContraseña(string user, string pass, string passvieja) {
            cliente.sservicioChat.cambiarContraseñaRequest inValue = new cliente.sservicioChat.cambiarContraseñaRequest();
            inValue.Body = new cliente.sservicioChat.cambiarContraseñaRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.passvieja = passvieja;
            cliente.sservicioChat.cambiarContraseñaResponse retVal = ((cliente.sservicioChat.Service1Soap)(this)).cambiarContraseña(inValue);
            return retVal.Body.cambiarContraseñaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cliente.sservicioChat.enviarMensajeResponse cliente.sservicioChat.Service1Soap.enviarMensaje(cliente.sservicioChat.enviarMensajeRequest request) {
            return base.Channel.enviarMensaje(request);
        }
        
        public void enviarMensaje(string user, string mensaje, string sala) {
            cliente.sservicioChat.enviarMensajeRequest inValue = new cliente.sservicioChat.enviarMensajeRequest();
            inValue.Body = new cliente.sservicioChat.enviarMensajeRequestBody();
            inValue.Body.user = user;
            inValue.Body.mensaje = mensaje;
            inValue.Body.sala = sala;
            cliente.sservicioChat.enviarMensajeResponse retVal = ((cliente.sservicioChat.Service1Soap)(this)).enviarMensaje(inValue);
        }
    }
}
